### PR TITLE
change interval time to 500 for all the slower queries

### PR DESCRIPTION
**Pull request by hkrishna**

### CODE REVIEW

**Comment by dianashk** [comment]
hmm, we're here fixing all this stuff in acceptance-tests, meanwhile there is a PR waiting to go in to start using fuzzy-tester and all these changes will be deleted. :disappointed: 

@orangejulius let's remember to merge this stuff into fuzzy-tester.

**Comment by orangejulius** [comment]
Yeah, i've been merging things back and forth as needed.

**Comment by dianashk** [comment]
@orangejulius, you're the best! thanks!

**Comment by orangejulius** [comment]
Aw shucks. Actually I intentionally created the fuzzy-tester repo by copying this repository, and then pruning the history of anything related to the test cases, leaving only the actual test suite code. That way we can merge branches between them without too much trouble. :)

**Comment by hkrishna** [comment]
im closing this PR in favor of https://github.com/pelias/acceptance-tests/compare/exponential-backoff

**Pull request closed without merging**
