### PR TITLE
fix test

### PR DESCRIPTION
**Pull request by missinglink**
disclaimer: I don't speak korean

I'm pretty sure this test case is wrong, I used an online translation tool I get:
`서울시청`->`City Hall` and nominatum corroborates that with: http://www.openstreetmap.org/way/198561926

The expected result `31 세종대로 서울시청 본관동` is a street address which translates to `31, Sejong University in Seoul City Hall main building` which is almost correct and the lat/lons match.

I think this is the result we *should* be returning is: http://pelias.mapzen.com/doc?id=osmway:198561926 although it's not properly searchable as we currently don't index the `alt_name:ko` tag, see: https://github.com/pelias/openstreetmap/blob/master/config/localized_name_keys.js

...so it's marked as `status:fail` for now

### CODE REVIEW

**Comment by orangejulius** [comment]
Disclaimer: I don't speak korean but I sit across from someone who does(thanks @hanbyul-here). And I have actually been to this building. 

What happened is there was an [old city hall](http://www.openstreetmap.org/way/198561929) which is now a library, and a [new city hall](http://www.openstreetmap.org/way/198561926#map=19/37.56633/126.97809). The new one was built in 2013 or so, meaning it's fairly recent. I think the open addresses data wasn't up to date until very recently, and that's what's causing problems. Searching for "서울시청" should return something for that main building, but unfortunately it returns the old openaddresses data first. The OSM data is totally correct and if we could just prioritize that, everything would be great.

I took a quick look and on staging things are even worse. The first result is [not even close to the right place](http://www.openstreetmap.org/way/166431170#map=17/37.49403/126.92119). The title translates to Seoul Youth Activity Center

**Comment by hanbyul-here** [comment]
I speak Korean :rainbow: !

I am not sure how test worked, but if it helps : what @orangejulius said is right and this http://pelias.mapzen.com/doc?id=osmway:198561926 data looks good for new building, but @missinglink , 31 세종대로 서울시청 본관동 was very ridiculously translated, (how could that  work?)  31 Sejong-daero, Seoul City Hall (main building)  would be right translation... if this matters at all :)

**Comment by missinglink** [comment]
I blame Mountain View

**Comment by dianashk** [comment]
I'm ok with either marking as a failure or pulling out into a PR. (prefer the PR approach since that's what we've been doing with other failing tests)

**Pull request merged**
