### PR TITLE
Add Street Synonyms test cases

### PR DESCRIPTION
**Pull request by missinglink**
Add Street Synonyms test cases to cover come of the cases in https://github.com/pelias/schema/pull/453

### CODE REVIEW

**Comment by orangejulius** [comment]
Tests look great. Do you think it might make more sense to put them in the existing [search_abbreviations](https://github.com/pelias/acceptance-tests/blob/master/test_cases/search_abbreviations.json) file?

**Comment by orangejulius** [comment]
Ah, one change to be made: there's a bug with the fuzzy-tester where combining `toLowerCase` and `abbreviateDirectionals` normalizers leads to errors. See the details over in https://github.com/pelias/fuzzy-tester/issues/201

**Comment by missinglink** [comment]
note the `R == Rue` test will no longer be valid since https://github.com/pelias/schema/pull/453#issuecomment-648166210

**Comment by orangejulius** [comment]
I combined these tests with the existing [search abbreviations](https://github.com/pelias/acceptance-tests/blob/master/test_cases/search_abbreviations.json) test suite, and marked them pass/fail as of the current master branch of pelias/schema.

After https://github.com/pelias/schema/pull/453 we will have a party where we mark several of the tests passing again!

**Pull request merged**
