### PR TITLE
Fix test regressions

### PR DESCRIPTION
**Pull request by orangejulius**
This takes @sevko's changes from a while back and expands them a bit for clarity. All the tests pass but we had to remove 1, and change the input string on 2. We should possibly just remove those 2 tests and bring them back as open issues/PRs instead.

### CODE REVIEW

**Comment by hkrishna** [comment]
:+1:

**Comment by dianashk** [comment]
Cool. Before merging, please link the new PRs with the moved tests.

**Comment by orangejulius** [comment]
We can't create the new PRs until after this is merged(a PR to remove something that is only removed in a branch would just be empty), but I'll do it immediately after.

**Comment by dianashk** [comment]
:+1: sounds good. thanks

**Comment by orangejulius** [comment]
Merged from the CLI. PRs coming after lunch :)

**Comment by orangejulius** [comment]
The tests removed by this branch are now in pull requests #66  and #67

**Pull request closed without merging**
