### PR TITLE
1426636804303:9, target admin entry and geoname record only

### PR DESCRIPTION
**Pull request by missinglink**
1426636804303:9, target admin entry and geoname record only

### CODE REVIEW

**Comment by missinglink** [comment]
@orangejulius is it cool to merge this?

**Comment by dianashk** [comment]
Looks legit. :+1:

**Comment by orangejulius** [comment]
giphy

**Comment by missinglink** [comment]
This is the best we can do, I have it from locals that there are a few different `Urnäsch` in Switzerland but the 'main' (largest) one is the "municipality in the canton of Appenzell Outer Rhodes", so unfortunately this may break in the future due to the ambiguity.

**Pull request merged**
