### PR TITLE
Remove failing tests

### PR DESCRIPTION
**Pull request by orangejulius**
All acceptance tests that were failing, even if the failure was expected, are removed.

Don't worry, they'll come back in individual pull requests.

12 tests total were removed, most from the feedback app that apparently used to be passing. One test was changed from failing to passing because it already was passing!

### CODE REVIEW

**Comment by dianashk** [comment]
:+1:

**Comment by orangejulius** [comment]
There was something slightly broken in production/stage(whichever env i ran against when I made this PR), that caused a few too many tests to fail, so there will be an update to this PR in a bit, stay tuned...

**Comment by orangejulius** [comment]
Ok, updated to reflect the correct set of failures. Also I removed each failing test in its own commit so they are easier to work with later.

**Comment by dianashk** [comment]
Cool :shipit:

**Comment by orangejulius** [comment]
merged on the CLI :)

**Comment by orangejulius** [comment]
The tests from this branch are back in PRs #72, #73, #74, #75, #76, #77, #78, #79, #80, #81, #82, and #83.

**Pull request merged**
