### PR TITLE
fail fast if apiResults doesnt exist

### PR DESCRIPTION
**Pull request by hkrishna**
This PR marks a test case as a failure if the API response does not have a results object and avoid the following error

```
TypeError: Cannot read property 'length' of undefined
    at evalTest (/Users/harishkrishna/code/pelias/acceptance-tests/run_tests.js:46:18)
    at Request._callback (/Users/harishkrishna/code/pelias/acceptance-tests/run_tests.js:220:21)
    at Request.self.callback (/Users/harishkrishna/code/pelias/acceptance-tests/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/harishkrishna/code/pelias/acceptance-tests/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/harishkrishna/code/pelias/acceptance-tests/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

### CODE REVIEW

**Comment by hkrishna** [comment]
@orangejulius review and comment at your convenience - thanks! :)

**Comment by orangejulius** [comment]
:+1:

**Comment by dianashk** [comment]
:shipit:

**Comment by orangejulius** [comment]
I merged this into this repo as well as the fuzzy-tester repo, which will contain our test code going forward.

**Pull request merged**
