### PR TITLE
Testing ngrams

### PR DESCRIPTION
**Pull request by dianashk**
Working through all the failing tests to determine which, if any, are release blockers.

Closes pelias/pelias#97

### CODE REVIEW

**Comment by missinglink** [comment]
Investigation of the remaining 11 regressions:

```bash
[1] "{"input":"new york, new york"}": No matching result found.
[2] "{"input":"newark airport"}": No matching result found.
[3] "{"lat":40.744243,"lon":-73.990342,"input":"new york city","details":false}": No matching result found.
[4] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":1}": No matching result found.
[5] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":"yes"}": No matching result found.
[6] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":"y"}": No matching result found.
[7] "{"input":"Ithaca farmers market"}": No matching result found.
[8] "{"input":"266 washington ave brooklyn"}": No matching result found.
[9] "{"input":"dulles airport"}": No matching result found.
[10] "{"input":"urnäsch, ch"}": No matching result found.
[11] "{"input":"Lake Cayuga, ny"}": No matching result found.
```

**Comment by missinglink** [comment]
[edit] after digging more I figured out that we have this issue: https://github.com/pelias/api/issues/143

**Comment by dianashk** [comment]
[3] caused by a mistake on my part. fixed the name in expected output to match that in locations.json
[4][5][6] all pass in prod and not stage because stage is behind prod with one [PR](https://github.com/pelias/api/pull/140). should be resolved next time we deploy API on stage

**Comment by dianashk** [comment]
:+1:

**Comment by missinglink** [comment]
the remaining issues have been individually addressed in PR's against master and should be merged in order to get master passing

**Pull request merged**
